### ISSUE TITLE
IWD One Page Checkout & Pay.nl

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#10]
Configured plugin correctly, payment methods are synced correctly, Frontend Checkout with IWD One Page Checkout hangs on ajax spinner and SyntaxError: JSON Parse error: Unexpected identifier "undefined". This seems to be a frontend javascript error due to combination Paynl_Payment and IWD_Opc.

**Comment by andypieters** [comment]
Please update the plugin, this issue is now resolved thanks to @bezigeboefjes
