### ISSUE TITLE
Issue with 'carrier_code' of null during checkout

### ISSUE THREAD

**Issue by wahidnory** [paynl/magento2-plugin#105]
Heya,

We currently updated this module on production.
What happened next is that all payment methods were showing 'blank'. Example:

The Afterpay in the image is a different module.
![image](https://user-images.githubusercontent.com/3277057/99525537-3d97e800-299a-11eb-89b6-ecd2dd458411.png)

After looking through some code it seems that this file and line:
https://github.com/paynl/magento2-plugin/blob/ab5cbec733509a76c2826dfb299038f99b041580/view/frontend/web/js/view/payment/method-renderer/default.js#L20

this
https://github.com/paynl/magento2-plugin/blob/a1477e05fee8d444eb0822519e4b29416d169016/view/frontend/web/js/view/payment/method-renderer/billink.js#L39

and 
https://github.com/paynl/magento2-plugin/blob/a1477e05fee8d444eb0822519e4b29416d169016/view/frontend/web/js/view/payment/method-renderer/ideal.js#L25

This line assumes that the carrier_code is always present.
Which in our case it isn't because the payment methods are being displayed on the same page or rather step.

And before the customer has a chance to fill in the shipping method, the payment tries to load itself.

Currently we can't use this module in our checkout.

Not sure how the bugreporting works here, but can this be addressed?

**Comment by woutse** [comment]
Thanks for your message. We'll look into this!

**Comment by woutse** [comment]
We are busy resolving this issue and will release a new version shortly.

**Comment by woutse** [comment]
We made changes in those files (See master repo). Can you confirm these changes solve this problem? If so we will publish this in a new release.

**Comment by wahidnory** [comment]
Heya,

Yes awesome this fixes our issue.

Thank you for quick handling! Much appreciated.

Will this be included in a release soon?

**Comment by woutse** [comment]
Great! No problem!
