### ISSUE TITLE
Checkout page - layout issue

### ISSUE THREAD

**Issue by bezigeboefjes** [paynl/magento2-plugin#11]
There is a layout issue with the header in the checkout page when the paynl module is  enabled. Please check attached screenshots. When the paynl module is disabled, the layout of the checkout page is normal. I've reset the theme to the default Luma, with original CSS stylesheets, to make sure it's not a theme error.

To reproduce:
```
# magento module:disable Paynl_Payment
=> Normal layout
# magento module:enable Paynl_Payment
=> Wrong header
```

**Wrong header:**
![paynl-enabled](https://cloud.githubusercontent.com/assets/20379631/18817606/417beb7c-8365-11e6-939e-c3fccde08a62.png)

**Normal header:**
![paynl-disabled](https://cloud.githubusercontent.com/assets/20379631/18817607/417e160e-8365-11e6-9073-eab39322d67b.png)

**Comment by bezigeboefjes** [comment]
Here's the fix:

In view/frontend/layout/checkout_index_index.xml:

```
Change:
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">

To:
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="checkout" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">

```

**Comment by andypieters** [comment]
Merged your pull request
