### ISSUE TITLE
Multisite wrong mailaddress in Paylink email

### ISSUE THREAD

**Issue by gjportegies** [paynl/magento2-plugin#117]
**Preconditions**
Magento 2.3.5
Paynl module 1.7.0

The multisite structure is as follows:
* **Website 1** _(sales + support email: info@website1.nl)_
    * Store NL _(sales + support email: info@website1.nl)_
* **Website 2** _(sales + support email: info@website2.nl)_
    * Store NL _(sales + support email: info@website2.nl)_
* **Website 3** _(sales + support email: info@website3.be)_
    * Store BE _(sales + support email: info@website3.be)_

**Issue**
When creating a new order, via the backend, in a multisite environment with the payment option Paylink the email with the Payment link contains the wrong Emailaddress.

The mailaddress given in the paymentlink mail is the Emailaddress set at the default config.

**Comment by woutse** [comment]
Thanks for your message. We will look into this asap.

**Comment by woutse** [comment]
Should be fixed in the 1.7.1 release.
