### ISSUE TITLE
Configuration setting: Payment from Applicable Countries

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#121]
What does this setting do in the admin backoffice of a certain payment method?

Thinking about this, it really doesn't make sense to us.

If it is based upon the shipping address, that doesn't make sense, because I can be Dutch, shipping to Germany for instance.

If it is based upon the store code, that also doesn't make sense, because I can speak German natively, but live in the Netherlands.

Wouldn't it be better to be able to set payment methods as 'preferred' for a certain storeview. And then at the end of the list of payment methods in the frontend, place a button to 'show all payment methods'. Clicking that would expand the list to show ALL payment methods enabled in the backend.

**Comment by woutse** [comment]
Thanks for your message. We will look into this!

**Comment by Kroellie** [comment]
I resolved it myself with the following strategy:

determine payment methods belonging to certain countries
add country classes to payment method divs
dynamically show / hide payment methods with css upon country change
added "show all methods" at bottom of list

Still need to figure out how to prevent reloading the payment methods on country changes, as this is now irrelevant.

**Comment by Kroellie** [comment]
@woutse What has been the resolution path for closure?
