### ISSUE TITLE
Composer 2.0 compatibility

### ISSUE THREAD

**Issue by Tjitse-E** [paynl/magento2-plugin#127]
> Deprecation Notice: Class Paynl\Payment\Controller\CsrfAwareActionInterface located in ./vendor/paynl/magento2-plugin/Controller/CsrfInterface22.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

I noticed this message when running `composer dump-autoload --optimize` for one of our projects. Magento 2.4.2 is already compatible with composer 2.0, so it makes sense to fix autoloading in this module.

**Comment by woutse** [comment]
Thanks for your message. We'll look into it!

**Comment by Tjitse-E** [comment]
@woutse  great, can't we leave the issue open until this is fixed?

**Comment by hostep** [comment]
Also noticing the same problem over here. @woutse, this issue should remain open until fixed, right?

It's probably time you start dropping Magento < 2.3 support? Or maybe figure out a better solution then [this hack](https://github.com/paynl/magento2-plugin/blob/466a402c2cc11dc250066c96de3fd2f0e14d647f/Controller/CsrfAwareActionInterface.php).

**Comment by woutse** [comment]
Thank for your message. We are working on this!

**Comment by woutse** [comment]
ready wednesday

**Comment by woutse** [comment]
This problem should now be solved with the latest release 2.0.0. Can you confirm? Thanks!

**Comment by hostep** [comment]
Thanks @woutse: I can confirm that the autoload warnings are gone using version 2.0.0 of your module! 🙂 

However, I'd advise you to change the constraints in the [`composer.json` file](https://github.com/paynl/magento2-plugin/blob/master/composer.json#L7-L9) a bit, since currently you can still install version 2.0.0 on Magento 2.2 using composer I think, I would suggest something like this which should allow Magento 2.3.0 until 2.4.x:
```json
    "magento/module-sales": "^102.0.0 || ^103.0.0",
    "magento/module-payment": "^100.3.0",
    "magento/module-quote": "^101.1.0",
```

**Comment by woutse** [comment]
Good to hear! Good point. We'll dig into this as well. I'll keep you informed here.

**Comment by woutse** [comment]
We investigated this. Changes will be made and available in the next release!

**Comment by hans2103** [comment]
@woutse  any updates on this one?

**Comment by woutse** [comment]
He! In the meanwhile above, lets say sub-issues, are already fixed! For composer 2.0 compatibilty we are waiting for Magento to approve our latest release.

**Comment by hans2103** [comment]
?? Should Magento approve 3th party extensions?

**Comment by woutse** [comment]
Approval for Magento marketplace. The plugin is now installable via composer 2.X!
