### ISSUE TITLE
Stock control

### ISSUE THREAD

**Issue by 6Ways** [paynl/magento2-plugin#14]
I experience a problem with stock control and pay.nl Magento Module 2. After placing an order, the inventory is reduced. However, when I cancel the payment when placing an order, the qty is increased by 2.

For example, for a product with a qty of one, there is only 1 qty reduced when placing an order, but then (during cancel) qty +2.

**Comment by andypieters** [comment]
Iam seeing the same thing here.
It looks like restoring the cart results in increasing the stocks, as well as canceling the order.

The strange thing is, if i order the last product, restoring the cast fails.
So i think there is something wrong in magento's restore cart function.

I will look into it, but it looks like a problem in magento itself

**Comment by lennartbee** [comment]
Are there any updates or workarounds on this? I found one other topic on this at http://magento.stackexchange.com/questions/146765/magento-2-restore-quote-cart-after-order-is-cancelled-failed and its basicly the only issue that keeps me from upgrading to magento 2

**Comment by andypieters** [comment]
I did,
You can remove the event that increases the stock on restoring a quote.
This will require an edit in a magento core file, so after updating magento the change will be gone.

In: vendor/magento/module-catalog-inventory/etc/events.xml

remove:
```xml
<event name="restore_quote">
  <observer name="inventory" instance="Magento\CatalogInventory\Observer\RevertQuoteInventoryObserver"/>
</event>
```

**Comment by lennartbee** [comment]
Thanx @andypieters , it works
