### ISSUE TITLE
Order comment compatibility

### ISSUE THREAD

**Issue by jeroen-hso** [paynl/magento2-plugin#141]
Order comment (https://github.com/boldcommerce/magento2-ordercomments) is not stored in order when using pay.nl payment methods. Default M2 bank transfer works.

**Comment by woutse** [comment]
Thanks for your message, we'll look into it.

**Comment by woutse** [comment]
Hi! We're going to make an addition to the plugin which should revolve this issue. I'll let you know when it's released.

**Comment by woutse** [comment]
HI, we expect this should work when using the `Enable additional validation` option in the newest release.
