### ISSUE TITLE
Checkout throws "Something went wrong with your request. Please try again later" error message during place order

### ISSUE THREAD

**Issue by my-brain-qlicks** [paynl/magento2-plugin#162]
Happens during the redirect to pay.nl

**Versions**
-  paynl/magento2-plugin:2.3.0
-  Magento 2.4.2

**Possible cause**
Additional validators are triggered during/despite afterPlaceOrder
/js/view/payment/method-renderer/default.js:168

**Comment by woutse** [comment]
Hi, thanks for your message. I could not reproduce this using the above versions. Have you tried the setting for `Enable additional validation`? If the problem persists please email support@pay.nl with, if possible screenshots and steps to reproduce.
