### ISSUE TITLE
After un-canceling cancel order items didn't uncanceled

### ISSUE THREAD

**Issue by guentur** [paynl/magento2-plugin#169]
As a result I cannot see information about ordered items in invoice. 
![image](https://user-images.githubusercontent.com/64845469/166454876-5407963f-f760-4cb3-8347-db2ce20ef8b2.png)
![image](https://user-images.githubusercontent.com/64845469/166455084-131dbb8d-b63d-402c-9158-b2649c009c8f.png)

Weird things is, message "PAY. canceled the order" caled only in case, when order become canceled (you can see on attachment bellow). But on attachments above you can see this message with status "Pending Payment"
![image](https://user-images.githubusercontent.com/64845469/166457462-2a152c32-c9db-4d80-831f-eeba06f0b85b.png)
(code from Paynl\Payment\Controller\Checkout\Exchange)

**Comment by woutse** [comment]
Thanks for your message. We are looking into it.

**Comment by woutse** [comment]
Hi, this is fixed in the newest release 2.8.0. Thanks again for reporting.
