### ISSUE TITLE
Giropay

### ISSUE THREAD

**Issue by 6Ways** [paynl/magento2-plugin#17]
The payment method "giropay" has been activated in various services within my Pay.nl account. However, I can not activate the payment method "giropay" in my Magento installation (both live and staging). I tested it with cache on and off and with different configuration settings. Unfortunately, my magento installation always says that the payment method must be activated within pay.nl.

Is there a solution or workaround for this problem?

**Comment by andypieters** [comment]
Just tested this in mij development store, but it seems to work fine, can you send an email to support@pay.nl
