### ISSUE TITLE
Paylink email template problems and Magento 2.4.4

### ISSUE THREAD

**Issue by visualwebs** [paynl/magento2-plugin#171]
In Paynl 2.8.0 I detect 2 problems, under Magento 2.4.4, and paylink emails.

1/ {{if show_order_in_mail}} is breaking the template, and rendering content between {{}} as plain text, looks not receiving properly the variable. Maybe 3rd party module affects.

2/ {{layout handle="sales_email_order_items" order=$order area="frontend"}} is not rendering. It uses old way with no scalar values.
If I use {{layout handle="sales_email_order_items" order_id=$order_id area="frontend"}} it breaks completely the template with "The entity that was requested doesn't exist. Verify the entity and try again.", because the module sends Order Increment ID instead the Order entity_id, and founds nothing. Maybe you can pass the variables "order_id" and "order_increment_id" in future versions.

Note: ACSD-47578 security patch was installed

**Comment by kevinverschoor** [comment]
Thanks for your message. We will look into this!

**Comment by escruickshank** [comment]
Thank you for your contribution! We have fixed this in v3.1.0. 
I will now close this issue.
