### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by YachYaroslav** [paynl/magento2-plugin#173]
Hello Pay.nl developers,

We are currently in the process of Magento upgrade to **2.4.6 version** with **PHP 8.2** which is marked as supported by Magento. But your module version "3.4.1" (which is the latest) throws PHP deprecation error [Usage of dynamic properties](https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties) when going to the order detailed page in Magento admin for example.

File path (relative): `Plugin/InstoreButton.php`
Dynamic class property: `$_request`

**Comment by escruickshank** [comment]
Hi @YachYaroslav, thank you for your input. We have prepared a fix for this and are planning a new release in the week commencing 17 april (week after next).

**Comment by escruickshank** [comment]
Hi @YachYaroslav, we have fixed this in our latest release (3.5.0). Thank you for your feedback! I will now close this issue.
