### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by samvh13** [paynl/magento2-plugin#18]
Hi,

after installing the pay.nl plugin everrything looked ok.
But when i wanted to go to /checkout i got a blank page. 
i dissabled the module and there wasn't any problem anymore.
Is there a known issue that can be solved quickly? is there a possibility that the extension isn't compatible with the magento one page checkout?
i already dissabled all magento payment and sending modules without any results.
our platform is magento 2.1.7 and uses php 7
you can check this problem on our testwebsite www.airsoftbeurs.be

with kind regards

**Comment by andypieters** [comment]
Hi,

Unfortunately the checkout fails silently, without any errors.
After installing did you run: php bin/magento setup:upgrade ?

Also does your php error log show any errors regarding this issue?

Best regards,

Andy Pieters

**Comment by bezigeboefjes** [comment]
I have running the plugin with version 2.1.7 and php7 (but not sure if I run the latest version of the plugin). Did you ran "magento setup:upgrade" after installation? After setup:upgrade you should do a recompile.

The full line I use is:
magento setup:di:compile; magento setup:static-content:deploy en_US; magento setup:static-content:deploy nl_NL; magento setup:static-content:deploy nl_BE; magento indexer:reindex; magento cache:enable; magento cache:flush; magento cache:clean

ps. Can you send me a mail on "github at bezigeboefjes.nl", I have some questions about the Belgium locale, and maybe I have a better translation file for you.

**Comment by samvh13** [comment]
hi,
i did everything as described and even more:

install thru composer
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy nl_NL
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush

but the blank page keeps comming back.

@andypieters where can i find the appropriate error log file? i'm srr but i normaly do not opperate on this level there i'm not a wizard in this stuff.

@bezigeboefjes ik heb jou command gebruikt en deze kan hij niet toepassen.
ik ben er wel zeker van dat de static content goed is geinstalleerd en de cache aan staat en gecleand is.

With kind regards

**Comment by samvh13** [comment]
@andypieters can i contact you in a more convenient way?
i think i found the log files for you, but i dont want to send them over this chat.

with kind regards

**Comment by andypieters** [comment]
Sure, you can email me at: support at pay.nl
