### ISSUE TITLE
Support for Hyvä Checkout

### ISSUE THREAD

**Issue by allrude** [paynl/magento2-plugin#182]
Hi paynl people, i read in the Hyvä Checkout Slack that you are working on module to support the Hyvä Checkout for Magento for release in September, is this correct?

Would be helpfull to know so we can plan for our customers, we would like to migrate but cant plan because we don't know wen and if paynl wil have a compatible module available ;-)

So if you can share some insights that would be helpfull, also if you need testers feel free to reach out.

**Comment by escruickshank** [comment]
Hi Ruud, thanks for your interest! We are working on this project with one of our partners. The aim is to start a pilot in September with a select few merchants.
If successful, we will make it available to a wider audience. 
I have put your name on our "wishlist" so we can keep you in the loop about future updates!
