### ISSUE TITLE
Payconiq redirects to success page when clicking "Return to webshop" before payment

### ISSUE THREAD

**Issue by janssensjelle** [paynl/magento2-plugin#184]
Payconiq seems to redirect customers to the success page instead of the shopping cart when they click "Return to webshop" without having pay for the order. 

This happens in the latest version 3.7.2

**Comment by escruickshank** [comment]
Hi! We have looked into this and decided to return a "cancelled" when "Return to webshop" is selected. This is consistent with other payment methods and ensures the customer is redirected back to the checkout. We are aiming to release this change at some point next week.

**Comment by escruickshank** [comment]
Hi @janssensjelle , this is now fixed in version 3.8.0. 
Thank you for reporting.

**Comment by janssensjelle** [comment]
This does not seem to have been fixed. I've got the 3.8.1 version but I still receive the thank you for your order page...

**Comment by janssensjelle** [comment]
This is resolved now as mentioned in #186
