### ISSUE TITLE
Issue #184 isn't resolved

### ISSUE THREAD

**Issue by janssensjelle** [paynl/magento2-plugin#186]
It was said that issue #184 would be resolved in a new release - but it still exists.

**Comment by escruickshank** [comment]
Hi @janssensjelle, thank you for your patience. Sorry to hear it is not working as expected. Let me follow up on this internally for you.

**Comment by escruickshank** [comment]
Hi @janssensjelle, can you please try again. You do not need to update the plugin. This has been a core change. 
I have just tested this on our Magento environment and am returned to the webshop. Hope this helps!

**Comment by janssensjelle** [comment]
This seems to work! Thank you @escruickshank
