### ISSUE TITLE
Remove Object Manager

### ISSUE THREAD

**Issue by jissereitsma** [paynl/magento2-plugin#190]
It seems somebody forgot to remove the object manager here: https://github.com/paynl/magento2-plugin/blob/75291e55c0638268294ac57cb19cf8a859a8f089/Model/Paymentmethod/Billink.php#L25

**Comment by escruickshank** [comment]
Hi! Thank you for your input. We will fix this in the next release.

**Comment by escruickshank** [comment]
Hi @jissereitsma , this has been included in release 3.9.1 so I will close this issue now. Thank you for your input!
