### ISSUE TITLE
Changing endpoints after payments

### ISSUE THREAD

**Issue by theboostcompany** [paynl/magento2-plugin#191]
It would be nice if we could changes these variables in the admin backend.

`    const FINISH_PAY = 'checkout/onepage/success';
    const PENDING_PAY = 'paynl/order/pending';
    const CANCEL_PAY = 'paynl/order/cancel';
    const FINISH_STANDARD = 'checkout/onepage/success';`

**Comment by escruickshank** [comment]
Hi! Thank you for your suggestion. I will discuss this with our Product Development Team.

**Comment by theboostcompany** [comment]
Thank you. Not sure you should mark it completed yet, but I'm looking forward for the solution.
