### ISSUE TITLE
Incorrect Payment method ID for Instore (PIN)

### ISSUE THREAD

**Issue by indykoning** [paynl/magento2-plugin#192]
In the Magento 2 plugin the Payment Method ID for the Instore (PIN) option has been set to 1729, this id does not work for enabling and creating pin transactions.
After setting the code to 1927 as the docs show it works properly
https://docs.pay.nl/paymentoptions#instore:~:text=Pinbetalingen%20betaaloptie%20ID-,1927,-Retourpinnen%20betaaloptie%20ID

I'm guessing this was a typo in during the creation of this payment method in the module

**Comment by woutse** [comment]
Thanks for your message! No, 1729 has always been the default, and still is. Maybe, in your case, it wasn't activated in your Pay admin? 1927 is a newer version, and will be the default in the near future.
