### ISSUE TITLE
Issue with latest version 3.11.0

### ISSUE THREAD

**Issue by aR0J5Zv** [paynl/magento2-plugin#194]
When you run php bin/magento se:up, you will get the error.
![image](https://github.com/paynl/magento2-plugin/assets/153855826/3aa3abf9-64a5-49b4-b9b7-b3ab00dead52)

![image](https://github.com/paynl/magento2-plugin/assets/153855826/8af3b9b0-da32-4622-9ac6-ec5567959484)

**Comment by Zaahed** [comment]
Seems to be fixed in the master branch. @woutse Can a new release be created?

**Comment by woutse** [comment]
Yes, should be fixed in 3.11.1!
