### ISSUE TITLE
Exchange failed

### ISSUE THREAD

**Issue by jorgb90** [paynl/magento2-plugin#195]
Using the latest version of the plugin we are getting the following error:

FALSE| Warning: Trying to access array offset on value of type null in /home/xxx/public_html/vendor/paynl/magento2-plugin/Model/PayPayment.php on line 264

**Comment by jorgb90** [comment]
It seems that for now it only fails on Apple Pay as payment method.

**Comment by woutse** [comment]
Thanks for your message, we'll look into it.

**Comment by woutse** [comment]
For now we advise to disable Follow Payment method, like this:
![afbeelding](https://github.com/paynl/magento2-plugin/assets/6763638/82184362-2f5c-4b7d-b890-9c5148c52268)

We'll fix this asap.

**Comment by woutse** [comment]
Issue resolved in release 3.11.2. Thanks again for reporting.
