### ISSUE TITLE
When a name is longer than 32 characters, provide a valid error

### ISSUE THREAD

**Issue by janssensjelle** [paynl/magento2-plugin#198]
When a customer has a firstname of longer than 32 characters, Pay returns an error message that is vague.

"Unfortunately something went wrong". 

In the log you can see this: Transaction start failed: PAY-405 - Parameter 'initials' is invalid: Input is too long, maximum length is 32 | 0

**Comment by woutse** [comment]
Thanks for your message. We'll look into it.

**Comment by woutse** [comment]
Checked, we'll make an adjustment, which will be available in the next release. Thanks for reporting!
