### ISSUE TITLE
PayNL marks quote as active in Controller/Checkout/Redirect without clear reason

### ISSUE THREAD

**Issue by npluimers** [paynl/magento2-plugin#199]
In `Controller/Checkout/Redirect` around line 90 it seems like you are making the old quote active again, so that you can redirect back to the cart if the payment does not exists. 

In the 'perfect flow' this works, since you are making the quote inactive again when the customer reaches the Checkout/Finish controller. However, when a customer decides to abandon after paying the quote remains active while the order is successfully paid. 

For us this causes issues with an abandoned cart flow. And I think this may be problematic for other magento 2 modules which expect the default magento way of work (marking the quote as inactive once the order is placed).

Could you please investigate?

**Comment by woutse** [comment]
Thanks for your message. We'll take a look, and let you know our findings.

**Comment by woutse** [comment]
Hi, we made an update (release 3.13.0). Hopefully this resolves your issue related to your abandoned cart flow.
