### ISSUE TITLE
Please add validation for all fields like issue number 198

### ISSUE THREAD

**Issue by janssensjelle** [paynl/magento2-plugin#200]
The same thing happens when the city is longer than X characters. Issue: [https://github.com/paynl/magento2-plugin/issues/198](issue)

Example: Molenbeek-Saint-Jean, Région de Bruxelles-Capitale

Please add it for all fields. And perhaps document the limits?

**Comment by janssensjelle** [comment]
@woutse any progress on this?

**Comment by woutse** [comment]
Good morning. Yes, this wil be solved in the upcoming release. Thanks for your message.

**Comment by woutse** [comment]
Hi, this fixed in the newest release 3.13.0. Thanks again for reporting.
