### ISSUE TITLE
Invoice address is missing city in Pay.nl 

### ISSUE THREAD

**Issue by JoostWan** [paynl/magento2-plugin#203]
For Billink, there is a check on the invoice address, but the city is missing. Upon reviewing the code, we identified this issue: https://github.com/paynl/magento2-plugin/blob/268c1b2f91f5c033419d7d7c446d012d7889b1a1/Model/PayPaymentCreate.php#L413C12-L413C91

Currently, the code references `$shippingAddress['city'`], but it should be `$invoiceAddress['city']`.

**Comment by woutse** [comment]
Thanks for your message. We'll fix this asap in 3.13.1.

**Comment by woutse** [comment]
Release 3.13.1 is live. Thanks again for reporting this issue.
