### ISSUE TITLE
PHP Requirement

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#204]
Hi,

Your readme indicates testing is done with PHP 8.1, however Magento 2.4.7 is specified as well as 'tested'. Magento 2.4.7 has the requirement of PHP 8.2, how does this work in your test cases?

The reason for asking, is that we're running PHP 8.3, and we're getting deprecation warnings on SubtractInventoryObserver.php(:32). This shows an issue with https://php.watch/versions/8.2/dynamic-properties-deprecated which I now fixed manually.

Thanks for looking into it!

**Comment by woutse** [comment]
Thanks for your message! We'll look into it and get back to you asap.

**Comment by woutse** [comment]
@Kroellie We didn't get this deprecated warning with the newest version of the plugin, but we're going to test the plugin with PHP 8.3 anyway and update the readme. And of course make changes if necessary.

**Comment by woutse** [comment]
We didn't see issues with PHP 8.3. If you do still see this deprecated message yourself, then please email this to support@pay.nl for further investigation, togerther with screenshots and steps to reproduce. 
In the next Magento plugin release we'll update the readme with "PHP Tested up to 8.3".
