### ISSUE TITLE
Riverty logo bijwerken

### ISSUE THREAD

**Issue by hans2103** [paynl/magento2-plugin#205]
Riverty heeft een nieuw logo en deze is nog niet bijgewerkt in de Magento 2 plugin

huidige logo:
https://github.com/paynl/magento2-plugin/blob/383e9d9c27b85ea2d1df28eb721c710ceb7f0ccc/view/frontend/web/logos/14.png

juiste logo
https://static.pay.nl/payment_profile_brands/100x100/14.svg

Zouden jullie de Magento plugin kunnen bijwerken, zodat het juiste Riverty logo er staat?
Dan staat het in onze Magento 2 checkout na update ook goed.

**Comment by woutse** [comment]
Goedemorgen! Dank voor je bericht. Zeker, we nemen dit mee in release 3.14.1. Release 3.14.0 staat al in de queue.

**Comment by hans2103** [comment]
@woutse kun je aangeven wanneer versie 3.14.1 beschikbaar komt? uren, dagen, weken?

**Comment by woutse** [comment]
We hebben het Riverty logo alsnog kunnen toevoegen aan release 3.14.0. Ik verwacht dat deze volgende week beschikbaar is.
