### ISSUE TITLE
Possibility to enable/disable module when installed

### ISSUE THREAD

**Issue by Melleschepers** [paynl/magento2-plugin#209]
At this moment there is no setting to switch the module on/off when installed. This is this is preferred / a requirement to work with multiple payment providers. 

It would be great to add this to the general settings.

**Comment by woutse** [comment]
Hi, thanks for your message. We'll look into it.

**Comment by woutse** [comment]
Obviously you can disable the module via CLI, using bin/magento module:disable Paynl_Payment.
What would be the great advantage of disabling the plugin in the plugin itself? Maybe you have an example usecase?
