### ISSUE TITLE
Feature query: change chosen payment method

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#21]
Hi, not sure if this is the way to do this request, but here it goes nonetheless: 

Would it be possible to change the payment method inside the pay.nl screen itself once a payment request has been initiated?

The problem I'm trying to resolve here is as follows: an order is being placed with a chosen payment method, the order is placed, and the pay.nl screen pops up. A customer decides to choose a different payment method, which is 50% of our cases because these days CC payments for example require passwords, or tokens or whatever. Customers hardly ever choose the correct payment method from the start. Now this customer clicks the only available option to him which makes sense: cancel. Subsequently the order in Magento is cancelled.

I'm investigating whether it is possible for us to re-initiate the payment, which makes sense, but I have to say, it also would be a nice feature from your end. Now the only remedy for getting this order payed is paying with the second-chance email, which is missed by the customer in 90% of the cases, resulting in two orders from the same customer, and questions from their end why they receive an e-mail while they have already payed (in their opinion).

Curious about your feedback, thanks in advance!

**Comment by andypieters** [comment]
Hi!
No sorry that isn't possible.
This would bypass settings in the webshop, for example payment fees.
The customer could pick a free payment method, and then switch to a more expensive option.

I don't really understand the problem, the plugin handles this in any way it can.
You can click the back button on the payment screen to go back to the shop.
Select a new payment method and retry.

Also, when you cancel the order, the customer is redirected back to the shop.
The cart should be intact, so the customer can choose a payment method and try again.

Our second chance script always checks if the customer already paid a different transaction.
Before sending an exchange email, we always check if on that day a customer using the same email already paid a transaction on your store.

**Comment by Kroellie** [comment]
Thanks for your thoughts. Perhaps I'm too opinionated by the way of working in M1 plugin. I've just tested it in M1, for us, there is no way for a customer to go 'back' into the cart, as the order is already made at that point.

In our M2 shop, which runs a test - pay.nl integration, there is only an API feedback button, and no 'real life like' payment screen. If I go 'back' with the browser button (which I don't think is a good practice from UI perspective) then indeed the cart is still filled. I would still vote for having a 'back to webshop button' in the webpage itself...

**Comment by andypieters** [comment]
Of course using the back button is not good practice, but many users do this.
Also, most payment methods have their own page, sometimes this can be on the page of the bank, we don't have control over that.

In M1 the cart should also be filled after cancelling or returning by using the back button.
Maybe you are using an old version of our plugin, it could help to update to the latest version.

Anyway, when you cancel the payment, the user should be redirected back to the shop, with the cart filled.
