### ISSUE TITLE
Exception  Payment model name is not provided in config!

### ISSUE THREAD

**Issue by Aquive** [paynl/magento2-plugin#210]
After installing i get this error when visiting a product page. Not sure why?

1 exception(s):
Exception #0 (UnexpectedValueException): Payment model name is not provided in config!

Exception #0 (UnexpectedValueException): Payment model name is not provided in config!
<pre>#1 Paynl\Payment\Model\ConfigProvider->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]

**Comment by woutse** [comment]
Hi, thanks for your message. Never seen this before. Did you try to remove and install the plugin again? Feels like an incomplete or corrupt installation.

**Comment by Aquive** [comment]
It seems it was an issue with our deployment tool. Thanks for the reply!
