### ISSUE TITLE
Charge fee per payment method

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#22]
In M1 plugin we can add charges to customer order per payment method, i.e. PayPal. This feature is lacking in M2 plugin.

**Comment by andypieters** [comment]
That is correct, but this can easily be added with another plugin.
For instance: https://store.fooman.co.nz/magento-extension-payment-surcharge-m2.html

**Comment by Kroellie** [comment]
Andy, We have installed your suggested plugin, but your extension does not conform to the following explanation they (Fooman) give us:

Good extension practice:
1) Upon switching of the payment method, the review section reloads
2) Custom Totals are displayed 
3) Custom Totals are displayed using their configured block 
4) Settings are honoured 
5) Totals sort order is honoured

As it appears, your extension does not comply with 1). 

We have added two fees for two paynl payment options: the totals box does not get refreshed during checkout, the fee does get applied however in the background.

**Comment by andypieters** [comment]
Iam guessing you are using some kind of onepage checkout.
You should set onepage checkout to reload after the payment method changes.

**Comment by Kroellie** [comment]
*sigh* you are correct, sorry, default magento checkout works. I'm getting rid of all Indian extensions.
