### ISSUE TITLE
Save payment url in magento order

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#23]
Is there a way to save the transaction payment url to the order? 

For example where it now says "iDEAL" in the customer order, make it instead: <a href="https://safe.pay.nl/payment/init/orderid/transactiontoken/xxx/yy">iDEAL</a>

This way a customer can always revisit the payment page to finish incase of an aborted session, or look up the status, or details for manual banktransfer.

**Comment by pietervanuhm** [comment]
Same for PayLink, if you choose for the PayLink option. 
Set the payment link to a comment directly to the customer with a link. Now the link is hardcode posted so customer cannot click on it.

**Comment by Kroellie** [comment]
Good to see you are actively helping your customers! I will create a new ticket for something else we would really like!

**Comment by woutse** [comment]
As you may have noticed we updated the paylink method functionality. Thanks for your input!
