### ISSUE TITLE
Wrong version in composer.json

### ISSUE THREAD

**Issue by Tjitse-E** [paynl/magento2-plugin#32]
Current release in composer.json is [1.4.1](https://github.com/paynl/magento2-plugin/blob/master/composer.json#L5). while the latest release is [1.4.2](https://github.com/paynl/magento2-plugin/releases/tag/v1.4.2)

**Comment by andypieters** [comment]
oops, i forgot to update the version in composer.json.
i'll create a new release 1.4.3, because i cant update an existing tag.
