### ISSUE TITLE
Magento 2.2.3 support

### ISSUE THREAD

**Issue by igorwulff** [paynl/magento2-plugin#37]
Hello Pay.nl developers,

We are planning to use Pay.nl for a new Magento 2 project where we intent to use the latest stable version from Magento (2.3.0). Can you specify if there is support for this version or that you are still testing compatibility with this latest version?

**Comment by andypieters** [comment]
Yes it works fine with magneto 2.3.0
Only thing is, in my composer.json i needed to edit the versions of the magento modules i'am depending on.
I've updated those in dev-master and it works fine in my development environment (2.3.0)

I'll create a new release now, so you can install the plugin via composer without errors.

**Comment by andypieters** [comment]
I just released version 1.4.8.
This version works with magento 2.3.0.
Like i said, nothing really changed, only the version of the magento modules the plugin depends on has been extended.
