### ISSUE TITLE
Security issue when different store views using the same order reference ID

### ISSUE THREAD

**Issue by istoutjesdijk** [paynl/magento2-plugin#40]
When you place an order in store 1 with order number 1000123 including payment and later place an order in store 2 which get assigned the same order number (1000123). You will be redirected to the Pay.nl payment method of the order of store 1 and when you click back you will see all customer data of the client/order of store 1 including the contents of the cart.

**Comment by andypieters** [comment]
Are you sure this is the case?
Orders are processed by the entity_id, which is the primary key in the database.

**Comment by istoutjesdijk** [comment]
Yes I reproduced the issue on a development area on Magento 2.3.1 with the latest Pay.nl plugin and also checked if the increment ID of the 2 orders would be the same but this is not the case. One customer even paid for the order of another customer. 

Apparently something is based on the ordernumber during payment. I also checked other payment methods but these are fine.

**Comment by andypieters** [comment]
@istoutjesdijk  Can you please contact us directly via support at pay.nl? so we can discuss details.
