### ISSUE TITLE
Magento market place codesniffer fail

### ISSUE THREAD

**Issue by cryptokittiecat** [paynl/magento2-plugin#42]
Environment: PHP 7.0.31 Magento 2.2 CE

php bin/magento deploy:mode:set production 

Enabling maintenance mode
Starting compilation
Something went wrong while compiling generated code. See the error log for details.
Disabling maintenance mode
Command returned non-zero exit code:
`/usr/bin/php -f /var/www/html/bin/magento setup:di:compile`

Errors : 1

Errors listed below must be fixed and resubmitted to Marketplace.
To prevent errors in the future please read our technical standards documentation.

File : /eqp-automation/temp/paynl/magento2-plugin/paynl-magento2-plugin-1.5.2/Controller/CsrfAwareActionInterface.php
Each interface must be in a file by itself
severity : 10
Line : 12
Column : 5
Source : PSR1.Classes.ClassDeclaration.MultipleClasses

**Comment by Kroellie** [comment]
There is also another error:

Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 54.0 MiBPHP Parse error:  syntax error, unexpected '?' in /var/www/site/vendor/paynl/magento2-plugin/Controller/Checkout/Exchange.php on line 68
