### ISSUE TITLE
after save API token and serviceID there is issue

### ISSUE THREAD

**Issue by jignesh6591** [paynl/magento2-plugin#7]
Fatal error: Class 'Paynl\Config' not found in app/code/Paynl/Payment/Model/Config.php on line 56

**Comment by andypieters** [comment]
Did you install it by using composer?
It looks like the dependency the SDK is not present

**Comment by jignesh6591** [comment]
no i have not used composer.i uploaded files and sdk then the err gone,.but
raised new issue

*Fatal error*: Class 'Curl\Curl' not found in *app/code/Paynl/Config.php* on
line *136*

On Sat, Apr 23, 2016 at 3:16 PM, Andy Pieters <notifications@github.com>
wrote:

> Did you install it by using composer?
> It looks like the dependency the SDK is not present
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/paynl/magento2-plugin/issues/7#issuecomment-213704533>
>



-- 
Thanks & Regards
Jignesh Chabhadiya
(+91)9558847447
Skype : jignesh.chabhadiya

**Comment by andypieters** [comment]
Th sdk uses this class https://github.com/php-curl-class/php-curl-class

**Comment by jignesh6591** [comment]
where to add this files?

On Sat, Apr 23, 2016 at 3:27 PM, Andy Pieters <notifications@github.com>
wrote:

> Th sdk uses this class https://github.com/php-curl-class/php-curl-class
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/paynl/magento2-plugin/issues/7#issuecomment-213705090>
>



-- 
Thanks & Regards
Jignesh Chabhadiya
(+91)9558847447
Skype : jignesh.chabhadiya

**Comment by andypieters** [comment]
I don't know i've only installed it by using composer


Op zaterdag 23 april 2016 heeft jignesh6591 <notifications@github.com> het
volgende geschreven:

**Comment by jignesh6591** [comment]
thanks for support. i found solution.

On Sat, Apr 23, 2016 at 3:37 PM, Andy Pieters <notifications@github.com>
wrote:

> I don't know i've only installed it by using composer
>
>
> Op zaterdag 23 april 2016 heeft jignesh6591 <notifications@github.com> het
> volgende geschreven:
>
> > where to add this files?
> >
> > On Sat, Apr 23, 2016 at 3:27 PM, Andy Pieters <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Th sdk uses this class
> https://github.com/php-curl-class/php-curl-class
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/paynl/magento2-plugin/issues/7#issuecomment-213705090
> >
> > >
> >
> >
> >
> > --
> > Thanks & Regards
> > Jignesh Chabhadiya
> > (+91)9558847447
> > Skype : jignesh.chabhadiya
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/paynl/magento2-plugin/issues/7#issuecomment-213705386>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/paynl/magento2-plugin/issues/7#issuecomment-213706221>
>



-- 
Thanks & Regards
Jignesh Chabhadiya
(+91)9558847447
Skype : jignesh.chabhadiya
