### ISSUE TITLE
Magento 2.1.1 component manager hangs

### ISSUE THREAD

**Issue by Kroellie** [paynl/magento2-plugin#9]
After installation:

composer require paynl/magento2-plugin
php bin/magento setup:upgrade
php bin/magento cache:clean

and entering component manager in backend, the ajax loader of component manager keeps spinning: a 500 error is served on http://<website>/setup/index.php/componentGrid/components

Calling this page shows this error page:
# 

An error occurred during execution; please try again later.

Additional information:

RuntimeException

File:
/var/www/html/magento2/setup/src/Magento/Setup/Model/PackagesData.php:88
Message:
Couldn't get available versions for package paynl/magento2-plugin
Stack trace:
#0 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
#1 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/html/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#12 {main}
#

**Comment by bezigeboefjes** [comment]
I have the same issue. I thought it was an upgrade issue from 2.0.9 to 2.1.1. But just removed  paynl/magento2-plugin in my test-environment and the component manager start working again.

To reproduce:

composer remove paynl/magento2-plugin
php bin/magento setup:upgrade
php bin/magento cache:clean
-> Component manager working

composer require paynl/magento2-plugin
php bin/magento setup:upgrade
php bin/magento cache:clean
-> Composer keeps spinning and error 500

**Comment by andypieters** [comment]
I will be looking into this today.
I did create a project on magento marketplace, but it isn't published yet, maybe that is the problem.

**Comment by andypieters** [comment]
Iam unable to reproduce this.
Can you please try it with the latest version of the plugin?

**Comment by bezigeboefjes** [comment]
Hi Andy,

This is still an issue, even with the latest version. I believe it's something with the marketplace.

Regards,
Erwin

**Comment by andypieters** [comment]
The marketplace version is being reviewed.
Technical review is ok, but for the mareting review i still need to write a manual and a product description.
I hope it will be live this week

**Comment by Kroellie** [comment]
Hi, Any update on this?

**Comment by andypieters** [comment]
Sorry for the delay, but the plugin is now available on marketplace.
The error should be gone now.
