### ISSUE TITLE
Select pay.nl as default payment method

### ISSUE THREAD

**Issue by thompalstra** [paynl/magento2-plugin#94]
Currently the PAY module does not register any payment methods resulting in us being unable to select (for example iDeal) as the default payment method.

Most payment providers are able to "add" their payment methods as shown:

![image](https://user-images.githubusercontent.com/17644484/96709826-80ff3680-139b-11eb-967b-10c975fa9b93.png)

How come under Pay there's only the paylink method and none of the others?

**Comment by woutse** [comment]
Thanks for your message. Could you send us an e-mail to support@pay.nl. Please include magento in the subject, this will forward your message directly to us.
